# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
baseurl: ""

# If you're using GitHub pages without custom domain, this is "[github_username].github.io". Prepend with "http://"
url: "https://snakehack.stair.ch/"
#url: "http://127.0.0.1:4000/"

# The ability to use custom themes.
style:
  theme: "zentralhack"


# Let people connect & engage with you through social media.
social:

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "SnakeHack | 11 Nov 2017"
  description: "SnakeHack is a one-day programming competition in Rotkreuz. Teams of students build bots playing the game snake. It takes place from 9am to 8pm on the new campus of the Fachhochschule Luzern (HSLU) informatics department."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "SnakeHack"
  description: "A one day programming competition in central Switzerland. <br><br>Build a snake bot and defeat your opponents"
  date:        "11 Nov 2017"
  location:    "Rotkreuz, Switzerland <br> Registration closed."


  hero:
    links:
      - text: "Event on Facebook"
        href: "https://www.facebook.com/events/156930364897350"


  about:
    description: >
      SnakeHack is a one-day programming competition in Rotkreuz in the Innovationspark Zentralschweiz on the HSLU campus.
      <br>
      Teams of students build web-based bots for the game "Snake" and let them compete against each other.
      <br>
      Whether you're a seasoned hackathon veteran or have never been to a programming competition before, SnakeHack will be an unforgettable event for you.

  # Frequently asked questions.
  faq:
    - question: "What is a programming competition?"
      answer: >
        Teams of students try to solve a specific task with code in a short period of time.
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending this competition is free.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at [Innovationspark Zentralschweiz, Suurstoffi 41 in Rotkreuz](https://www.google.ch/maps/place/Suurstoffi+41,+6343+Rotkreuz+ZG).
    - question: "Will there be food?"
      answer: >
        Yes, there is free food. We will provide food, snacks and drinks for everyone through the day.
    - question: "Help, I can't code."
      answer: >
        You don't need to be a coding champ, basic coding skills are enough and there will be help available.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        They work with over 200 Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  timeline:
    days:
      - day: "Saturday, Nov 11th"
        events:
          - title: "Registration"
            time: "8:30 - 9:00"
            place: ""
          - title: "Introduction"
            time: "9:00"
            place: ""
          - title: "Lunch"
            time: "12:00 - 13:00"
            place: ""
          - title: "Dinner"
            time: "17:30 - 18:30"
            place: ""
          - title: "Finals"
            time: "18:30"
            place: ""
          - title: "End"
            time: "20:00"
            place: ""

  sponsor:
    sponsorus: >
      Interested in sponsoring us? Contact us via <a href="mailto:event@stair.ch">event@stair.ch</a>
    mainSponsor:
#      - image: "images/careers-service.jpg"
#        url: "https://www.bbv.ch/"
#        description: >
#          bbv Software Services AG
    sponsors:
      - image: "images/logo-pwc.jpg"
        url: "https://www.pwc.com/"
        description: >
          PwC
      - image: "images/logo-careers-service.jpg"
        url: "https://www.hslu.ch/en/careers/"
        description: >
          Careers Service
    sponsorsSmall:
      - image: "images/logo-monday.png"
        url: "http://www.monday-energy.ch/"
        description: >
          Monday energy

      - image: "images/logo-eltony.jpg"
        url: "http://www.tonymate.com/"
        description: >
          El Tony Mate
      - image: "images/logo-eichhof.png"
        url: "http://www.eichhof.ch/"
        description: >
          Eichhof
    sectionSupport:
      - image: "images/logo-innovationspark.png"
        url: "https://www.building-excellence.ch/"
        description: >
          Innovationspark Zentralschweiz
      - image: "images/logo-stair.png"
        url: "https://www.stair.ch"
        description: >
          Student Association Informatics Rotkreuz
      - image: "images/logo-hslu.svg"
        url: "https://www.hslu.ch/de-ch/informatik/"
        description: >
          Hochschule Luzern â€“ Informatik
      - image: "images/logo-mlh.png"
        url: "https://mlh.io/"
        description: >
          Major League Hacking


# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
